### ISSUE TITLE
ethminer 0.19.0-alpha.0 issue

### ISSUE THREAD

**Issue by deke997** [AndreaLanfranchi/neth-proxy#5]
Can't get this to work with ethminer 0.19.0-alpha.0. 

Looks like something is off with how the API response is handled.

Any ideas?

```
Unhandled Exception: Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'System.Json.JsonPrimitive' to type 'System.Json.JsonObject'.
   at nethproxy.Clients.Client.ProcessAPIResponse(String message) in D:\NetProjects\stratumProxy\neth-proxy\Clients\Client.vb:line 589
   at nethproxy.Clients.Client._Lambda$__R7-7(Object& a0, String a1)
   at nethproxy.Sockets.AsyncSocket.QueueData() in D:\NetProjects\stratumProxy\neth-proxy\Sockets\AsyncSocket.vb:line 379
   at nethproxy.Sockets.AsyncSocket.ReceiveSocketData(SocketAsyncEventArgs e) in D:\NetProjects\stratumProxy\neth-proxy\Sockets\AsyncSocket.vb:line 412
   at nethproxy.Sockets.AsyncSocket.OnAsyncIOCompleted(Object sender, SocketAsyncEventArgs e) in D:\NetProjects\stratumProxy\neth-proxy\Sockets\AsyncSocket.vb:line 579
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketFlags flags, SocketError socketError)
   at System.Net.Sockets.SocketAsyncEventArgs.TransferCompletionCallbackCore(Int32 bytesTransferred, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError socketError)
   at System.Net.Sockets.SocketAsyncContext.BufferMemoryReceiveOperation.InvokeCallback(Boolean allowPooling)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessAsyncOperation(TOperation op)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.<>c.<.cctor>b__18_0(Object op)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()System.InvalidCastException: Unable to cast object of type 'System.Json.JsonPrimitive' to type 'System.Json.JsonObject'.
   at nethproxy.Clients.Client.ProcessAPIResponse(String message) in D:\NetProjects\stratumProxy\neth-proxy\Clients\Client.vb:line 589
   at nethproxy.Clients.Client._Lambda$__R7-7(Object& a0, String a1)
   at nethproxy.Sockets.AsyncSocket.QueueData() in D:\NetProjects\stratumProxy\neth-proxy\Sockets\AsyncSocket.vb:line 379
   at nethproxy.Sockets.AsyncSocket.ReceiveSocketData(SocketAsyncEventArgs e) in D:\NetProjects\stratumProxy\neth-proxy\Sockets\AsyncSocket.vb:line 412
   at nethproxy.Sockets.AsyncSocket.OnAsyncIOCompleted(Object sender, SocketAsyncEventArgs e) in D:\NetProjects\stratumProxy\neth-proxy\Sockets\AsyncSocket.vb:line 579
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketFlags flags, SocketError socketError)
   at System.Net.Sockets.SocketAsyncEventArgs.TransferCompletionCallbackCore(Int32 bytesTransferred, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError socketError)
   at System.Net.Sockets.SocketAsyncContext.BufferMemoryReceiveOperation.InvokeCallback(Boolean allowPooling)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessAsyncOperation(TOperation op)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.<>c.<.cctor>b__18_0(Object op)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

**Comment by sniper-noob** [comment]
@AndreaLanfranchi @deke997 Yes it works only with ethminer-ethash ver. 0.15.0 . just tested today.
